apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "f1-strategy-engine.fullname" . }}-worker
  labels:
    {{- include "f1-strategy-engine.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "f1-strategy-engine.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "f1-strategy-engine.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "f1-strategy-engine.serviceAccountName" . }}
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "f1-strategy-engine.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secrets.name }}
          readinessProbe:
            exec:
              command:
                - celery
                - -A
                - backend.workers.celery_app
                - inspect
                - ping
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
