"""add driver_positions table

Revision ID: 9cd0463cbe60
Revises: 9220791a906d
Create Date: 2026-08-27 19:47:30.812489

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cd0463cbe60"
down_revision: str | None = "9220791a906d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "driver_positions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=False),
        sa.Column("lap_number", sa.Integer(), nullable=False),
        sa.Column("timestamp_in_lap", sa.Float(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"]),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_driver_positions_driver_id"), "driver_positions", ["driver_id"], unique=False
    )
    op.create_index(
        op.f("ix_driver_positions_session_id"), "driver_positions", ["session_id"], unique=False
    )
    op.create_index(
        "ix_driver_positions_session_lap",
        "driver_positions",
        ["session_id", "lap_number", "timestamp_in_lap"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_driver_positions_session_lap", table_name="driver_positions")
    op.drop_index(op.f("ix_driver_positions_session_id"), table_name="driver_positions")
    op.drop_index(op.f("ix_driver_positions_driver_id"), table_name="driver_positions")
    op.drop_table("driver_positions")
    # ### end Alembic commands ###
