"""add replay car numbers

Revision ID: e208a452244d
Revises: a795cb2f7af8
Create Date: 2026-09-26 15:09:05.719894

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e208a452244d"
down_revision: str | None = "a795cb2f7af8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "replay_car_numbers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=False),
        sa.Column("car_number", sa.String(length=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "car_number", name="uq_replay_car_numbers_session_number"
        ),
        sa.UniqueConstraint("session_id", "driver_id", name="uq_replay_car_numbers_session_driver"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("replay_car_numbers")
    # ### end Alembic commands ###
