"""add total_laps to sessions

Revision ID: 14f9dc94f3c5
Revises: a4677e4792a6
Create Date: 2026-09-18 23:55:14.933866

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14f9dc94f3c5"
down_revision: str | None = "a4677e4792a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("total_laps", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "total_laps")
    # ### end Alembic commands ###
